jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v5
name: release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
