jobs:
  translate:
    permissions:
      discussions: write
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: lizheming/github-translate-action@1.1.2
      with:
        APPEND_TRANSLATION: true
        IS_MODIFY_TITLE: true
name: translator
on:
  repository_dispatch:
    types: trigger-ga___translator.yml
